import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import clsx from 'clsx'

const font = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
